[package]
name = "webot-frontend"
version = "1.0.7"
description = "WeBot frontend desktop app powered by Tauri 2.0"
edition = "2021"

[lib]
name = "webot_frontend_lib"
crate-type = ["staticlib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.2.0", features = [] }

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri = { version = "2.8.5", features = ["tray-icon"] }
webot-service-rs = { path = "../../service-rs" }
rfd = "0.15.4"
base64 = "0.22.1"
reqwest = { version = "0.12.24", default-features = false, features = ["json", "rustls-tls"] }

[features]
default = []
